name: CI/CD Pipeline for dozie
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: check-out code
        uses: actions/checkout@v2

      - name: setup dotnet core
        uses:  actions/setup-dotnet@v1
        with: 
           dotnet-version: '7.0.x'

      - name: build project  
        run: dotnet build

      - name: run dotnet project
        run: dotnet run
 
